### ISSUE TITLE
since update to v0.7.4 - error: "cannot set properties of null (setting 'onclick')"

### ISSUE THREAD

**Issue by PeterKawa** [custom-cards/flex-table-card#117]
Hi,

Since version v0.7.4 I get this error in lovelace cards where i use flex-table-card in combination with auto-entities card:
`cannot set properties of null (setting 'onclick')`
When I install v0.7.3 again there's no error whatsoever.

YAML of one such card:
```
type: custom:auto-entities
filter:
  include:
    - entity_id: switch.*
      state: 'on'
  exclude:
    - entity_id: switch.*kaar*
    - entity_id: switch.*kers*
    - entity_id: switch.*lant*
    - entity_id: switch.rol*
    - entity_id: switch.*led*
    - entity_id: switch.*lamp*
    - entity_id: switch.*cloud*
    - entity_id: sensor.*state*
    - entity_id: curtain.8
card:
  type: custom:flex-table-card
  max_rows: 35
  strict: true
  clickable: true
  title: (flex-table + auto-entities)
  css:
    table+: 'border: 20;'
  columns:
    - name: ''
      data: name
      icon: mdi:lightbulb-alert-outline
      suffix: ''
      align: center
    - name: ''
      data: state
      icon: mdi:lightbulb-on-10
      align: right
    - name: Last update
      data: last_updated
      suffix: ' hrs'
      fmt: hours_passed
    - name: Last update
      data: last_updated
      suffix: ' min'
      modify: Math.round(((Date.now() - Date.parse(x)) / 36000.) * 0.6 )
sort:
  method: friendly_name
  reverse: false
  numeric: false
  ignore_case: true
```

Screenshot of error:
![image](https://github.com/custom-cards/flex-table-card/assets/74005072/952e2f49-5110-4b6e-89f5-4be39bd91654)

When editing the card, it shows no error at the bottom, but the preview on the right only shows an alert:
![image](https://github.com/custom-cards/flex-table-card/assets/74005072/47214caa-7545-4f98-a84d-9adaa2efaf1e)

![image](https://github.com/custom-cards/flex-table-card/assets/74005072/c7945e22-8b6f-4f79-a746-214cf9194a60)

Thanks in advance,
Peter
