### ISSUE TITLE
Feature Request: configurable empty behavior 

### ISSUE THREAD

**Issue by daringer** [custom-cards/flex-table-card#12]
Allow setting an `on_empty` configuration parameter to define the output behavior, if no rows are created.
```yaml
on_empty:
    # to hide the entire flex-table (default: false)
    hide: true
    # if `!hide` show the following text instead of content
    text: "my story why there are no rows to show"
    # do not show the column headers (default: false)
    hide_headers: true
```
