### ISSUE TITLE
[Feature Request] Additional columns for independent auto-entities filter

### ISSUE THREAD

**Issue by AleXSR700** [custom-cards/flex-table-card#124]
Hallo Markus,

great card and exactly what I was looking for after trying and failing to create nice tables with the stock cards :)

Well, almost exactly, because I am wondering if there is any way of filling a table with a second set of filters.

Background is quite simple: I would like to create a table that shows all climate information of my home.
But not all of that information is available in one entity.

<img width="613" alt="image" src="https://github.com/custom-cards/flex-table-card/assets/57034871/c68f01d2-ea4d-402c-a515-66e2bf49b3a9">

As you can see, most information is available by adding multiple sensors to the MQTT discovery topic. But this is not possible for other domains and the MQTT HVAC integrations does not allow for battery information.

So in the above table, battery information is missing.

It would be really cool if somehow the flex-table-card could create additional columns for a new set of filters.

MAybe something like:
```
type: custom:flex-table-card
entities:
  include: climate.*
clickable: true
columns:
  - name: ''
    data: friendly_name
    align: left
  - name: Target Temperature
    data: temperature
    align: center
    modify: if(x.length == 0){"-"}else{x}
  - name: Current Temperature
    data: current_temperature
    align: center
    modify: if(x.length == 0){"-"}else{x}
  - name: Current Humidity
    data: current_humidity
    align: center
    modify: if(x.length == 0){"-"}else{x}

entities_2:
  include: sensor.xiaomi*battery*
clickable: true
columns_2:
  - name: Battery
    data: state
    align: center
    modify: if(x.length == 0){"-"}else{x}

```

`entities_x` is then shown in `columns_x`. Of course flexible if you force the card to start with `entites` or replace it with `entities_1` but for backward compatibility it would probably be best to have the first one without suffix and then the additional ones with suffix.

Would be extremely cool if something like this were possible.

Thank you for your consideration.

Viele Grüße
Alex
