### ISSUE TITLE
Sorting not working (maybe bug, maybe FR)

### ISSUE THREAD

**Issue by AleXSR700** [custom-cards/flex-table-card#126]
It seems that sorting only works on attributes that are being displayed in the table rather than all attributes of the entity that is being displayed.

I am displaying only the state but this seems to mean that I can only sort by state and not by friendly_name of the entity who's state I am displaying.

```
  - type: custom:flex-table-card
    entities:
      include:
        - sensor.eq3*valve
    sort_by: friendly_name
    columns:
      - name: <div>Valve<br><br>%</div>
        data: state
```
So even though the included entities all have friendly_names, sorting does nothing except when sorting by state (the only attribute being displayed).

Ideally, like in auto-entities, sorting should be possible by any attribute of the entities selected in `include`.

Would that be possible?

Or is that maybe even the intended way?

Thank you
Alex
