### ISSUE TITLE
Dictionary keys and values ​​as table rows

### ISSUE THREAD

**Issue by rybakov-ks** [custom-cards/flex-table-card#148]
Hello. I am trying to create a custom:flex-table-card using data in the following JSON format:
```
{
  "entity_id": "sensor.model_results",
  "state": "Detected",
  "attributes": {
    "objects_detected": {
      "car": 5,
      "person": 2,
      ...,
      ...
    }
  }
}
```
Here is the card configuration:
```
type: custom:flex-table-card
title: Processing Results
entities:
  - sensor.model_results
columns:
  - name: Class
    data: attributes
    modify: Object.keys(x.objects_detected).join(", ")
  - name: Count
    data: attributes
    modify: Object.values(x.objects_detected).join(", ")
```
The data car and person are displayed in a single row. I need each object to be displayed in a separate row in the table. How can this be achieved?

![example](https://github.com/user-attachments/assets/365ed5cd-d641-4060-8b05-6b026336ccf8)
