### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Nickduino** [custom-cards/flex-table-card#149]
I got no answer [on the community thread](https://community.home-assistant.io/t/flex-table-card/461173/262), so I'm trying here. I could not find similar issues on Github either.

If I leave the card alone (and let `sort_by: state+` do its thing), It works. But if I click on the headers, I don't get the right sorting:

![image](https://github.com/user-attachments/assets/76adb9da-6ab5-4bef-baaa-702d9bca88a5)

The "Distance" column sorts properly. The last one (which displays the age of the information) doesn't (even if I remove the prefix and show only numbers:

![image](https://github.com/user-attachments/assets/2b3a709f-2c5f-443c-b45f-427c7d88b5de)

The sorting by price column doesn't work either if I remove `sort_by: state+`
I also tried `sort_unmodified = true` just in case: the behavior is the same

```
type: custom:flex-table-card
sort_by: state+
clickable: true
max_rows: 5
entities:
  include:
    - sensor.station_*SP98
columns:
  - data: entity_picture
    align: center
    name: ""
    modify: "'<img src=\"' + x + '\"style=\"height: 35px\">'"
  - data: fuel_type
    align: center
    name: ""
    icon: mdi:gas-station
  - data: address,city
    multi_delimiter: ", "
    align: left
    name: ""
  - icon: mdi:currency-eur
    data: state
    name: ""
    align: center
  - data: distance
    modify: x + " km"
    name: Distance
  - icon: mdi:calendar-clock
    name: ""
    data: days_since_last_update
    align: center
    prefix: J+
layout_options:
  grid_columns: full

```
