### ISSUE TITLE
Broken scrolling under ha 2015.1.1

### ISSUE THREAD

**Issue by sabbie-github** [custom-cards/flex-table-card#159]
Card works, but css no longer regulates card size to make it scrollbar. Card appears full size with full list, ignoring size limit in css that previously made it scrollable.
My code that worked before (limited height, scroll list), now renders the complete list ignoring size limit. What am I doing wrong?
Was "overflow auto" tried overflow y but doesn't work. Auto worked before to make table scrollable.

```
type: custom:auto-entities
filter:
  include:
    - integration: tplink_deco
  exclude:
    - state: not_home
card:
  type: custom:flex-table-card
  title: Mesh Connected Devices
  clickable: true
  strict: true
  columns:
    - data: deco_device
      name: Deco
      modify: if(x.length == 0){""}else{x}
    - data: friendly_name
      name: Client Name
    - data: ip
      name: Client IP
    - data: interface
      name: Network
  sort_by:
    - Deco+
  css:
    table+: "padding: 10px"
  card_mod:
    style: |
      ha-card {
        overflow-y: scroll;
        max-height: 650px;
      }
sort:
  method: friendly_name
show_empty: false
strict: true

```
