### ISSUE TITLE
Feature Request: Icons instead of name

### ISSUE THREAD

**Issue by gw1gw1** [custom-cards/flex-table-card#16]
Hi,

It would be great if we could have an icon as column headers instead of names.

Thanks

![icons-as-header](https://user-images.githubusercontent.com/47014001/68092865-e5c23800-fe8f-11e9-9a43-099841451ea6.jpg)

**Comment by daringer** [comment]
uha, good idea. 

For sure easy to do a *hacky* solution, but there likely is a "right way" in homeassistant. The regular entity card does it, I guess. So do you wanna choose from the common icon-set by name, or do you want to actually insert arbitrary icons by linking?
But yeah, shouldn't be to challenging: consider it *in progress* :+1:

**Comment by gw1gw1** [comment]
Ideqlly I would like to be able to select the icon I want. Maybe adding a new option at 2nd-level options like icon and then be able to pick the mdi icon we want.

```
type: custom:flex-table-card
            title: Temperature & Humidity
            entities:
              include:
                - sensor.0x00158d00032316c2_temperature
                - sensor.0x00158d000346476a_temperature
                - sensor.0x00158d0002b54177_temperature
                - sensor.0x00158d0002b5b640_temperature
                - sensor.0x00158d0002b5419e_temperature
                - sensor.0x00158d0002b51986_temperature
                - sensor.0x00158d0002b54160_temperature
            columns:
              - name: Room
                attr: friendly_name
              - name: Temperature
                icon: mdi:temperature-celsius
                attr: temperature
                suffix: °C
              - name: Humidity
                icon: mdi:water
                attr: humidity
                suffix: '%'
```
