### ISSUE TITLE
Header is shown twice

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/flex-table-card#162]
2025.2.1
0.7.8

Observed a very weird issue which was not there before:

![Image](https://github.com/user-attachments/assets/f73c6854-c9eb-488a-af07-0961bfef9956)

Note that a header is shown twice.
Code Inspector shows 2 `ha-card` elements:

![Image](https://github.com/user-attachments/assets/3f66cf68-7dcc-408f-a13e-d3d095bc7ae5)

A code was simple:
```
      - type: custom:auto-entities
        filter:
          include:
            - entity_id: sun.sun
        card:
          type: custom:flex-table-card
          columns:
            - name: state
              data: state
            - name: state
              data: state
```
Need more time for a proper testing.
Could be related to other plugins like card-mod. auto-entities.
