### ISSUE TITLE
Script as data input does not update on change

### ISSUE THREAD

**Issue by Gultak** [custom-cards/flex-table-card#163]
I use the script metod to get a list of departures from an attribute of my GTFS sensor.

The script is called via:
```
  action: script.get_departures
  action_data:
    entity: <my GTFS entity>
```

The script reads the attribute of the supplied enttity and generates a list of data elements, which are then rendered into a list of departures.

This works quite nice, but the table does not update when the data in the entity attribute changes (as scripts do not listen to events).

When I add a non-empty `entities` config to the table card, it breaks, probably because it then tries to call the action on the entity as the `target` of the script, which seems to not be supported by HA.

Is there a way to add the entity to listen for change events to another way?

**Comment by iamjoshk** [comment]
This was a challenge to get working, but the forthcoming updated docs provided some guidance. My script calls an action that only provides a response and doesn't update an entity.

This is the script I ended up with:
```
sequence:
  - data: {}
    action: discogs_sync.download_collection
    response_variable: discogs   
  - variables:
      records: |
        {% set response = { entity_id[0]: discogs } %} {{ response }}
  - stop: All done
    response_variable: records
alias: Discogs Download Collection
```

and my flex-table-card:
```
type: custom:flex-table-card
enable_search: true
action: script.discogs_download_collection
entities:
  - sensor.my_collection
sort_by:
  - Artists
  - Year
columns:
  - name: Cover
    data: collection.thumb
    modify: "x ? `<img src=\"${x}\" style=\"height:50px;\"/>` : \"\""
    align: center
  - name: Artists
    data: collection.artists
    modify: x.map(a => a.name.replace(/^The /, "")).join(", ")
  - data: collection.title
    name: Title
  - data: collection.year
    name: Year
  - name: Format
    data: collection.formats
    modify: "x && x.length > 0 ? x[0].name : \"\""
  - name: Genre
    data: collection.genres
    modify: if(x.length == 0){""}else{x}
  - name: Styles
    data: collection.styles
    modify: if(x.length == 0){""}else{x}
grid_options:
  columns: full
  rows: auto
card_mod:
  style: |
    ha-card {
      overflow: auto;
      max-height: 700px;
    }
```

`sensor.my_collection` is passed through from the card to the `entity_id` in the script. When the entity updates, the card data will update.
