### ISSUE TITLE
Performing Actions in 0.7.9 only working partially

### ISSUE THREAD

**Issue by derandiunddasbo** [custom-cards/flex-table-card#168]
I'm trying to get the new Performing Actions feature working, but it doesn't work as expected. 

When performing actions on the second column in the example below, the response animations are shown (i.e. flashing the background color on both tap actions or showing the circle for the hold action). 

But neither the script is called, nor the browser_mod popup is shown. However, some other actions seem to be working, at least somehow. For example, the `action: url` in the `hold_action` is actually opening a new tab with the given URL. 

If `clickable: true` is set, the regular more-info dialog is shown in any case, i.e. even when performing the `hold_action`, besides opening the URL in a new tab the more-info dialog is popping up on the dashboard.

If `clickable` is ommitted or set to`false`, the only difference is, that the more-info dialog doesn't appear. Everything else works (or doesn't work) as described above.

```yaml
type: custom:auto-entities
filter:
  include:
    - options: {}
      entity_id: sensor.active_issues
card:
  type: custom:flex-table-card
  auto_format: true
  clickable: true
  columns:
    - data: friendly_name
    - data: entity_id
      tap_action:
        action: call-service
        service: script.some_server_side_popup
        service_data:
          browser_id: THIS
      double_tap_action:
        service: browser_mod.popup
        data:
          title: TEST
          target:
            device_id: THIS
          content: |
            <p> <b>TEST</b> </p>
      hold_action:
        action: url
        url_path: https://www.nabucasa.com
  
```
