### ISSUE TITLE
Question/Feature request: exclude results from table?

### ISSUE THREAD

**Issue by timdonovanuk** [custom-cards/flex-table-card#20]
I see its possible to exclude entities, but is it possible to exclude a row based on a value (which may come from an attribute)? 

Thanks.

**Comment by daringer** [comment]
no currently this is not possible,
the way to implement this would likely be a `skip_if` config field, which might match with an arbitrary regex and if it matches with the contents of a specific cell, the full row should get skipped... mmh, will have to think about that...

another option currently possible would be to add another column (e.g., "show_row"), make `hidden`, make sure its content is either "0" or "1", finally apply a sorting based on this column and use `max_rows` to show just the rows containing "0". Downside of this approach would be an always fixed number of rows shown...

**Comment by daringer** [comment]
looks like `skip_if` is not even necessary, there already is the `strict:` property, it will not show any row containing `null` as value, means you could easily exploit this using `modify`:
```yaml

type: 'custom:flex-table-card'
strict: true
title: sometitle
columns:
  - attr: node_id
    name: NodeID
    modify: '(x > 10) ? null : x'
  - name: Name
    prop: name
```
just tried it, works flawlessly. `modify:` is here just checking, if `node_id > 10` and returns `null`, if true, this `null` is then leading to the row being deleted. As `strict: true` ensures that no rows with `undefined` or `null` cell-contents are shown.
