### ISSUE TITLE
Request: Manually order entity list

### ISSUE THREAD

**Issue by cryptooth** [custom-cards/flex-table-card#3]
Is it possible to manually set entity order?
for example in the order of the list.

**Comment by daringer** [comment]
Can not really understand what you mean, could you maybe write how you think this might look like in the .yaml configuration.

**Comment by cryptooth** [comment]
This is my config:
(This is a class timetable.)

```
      - type: custom:flex-table-card 
        sort_by: friendly_name
        title: Dersler
        entities:
          include: 
            - **sensor.birinci_ders**
            - sensor.ikinci_ders
            - sensor.ucuncu_ders
            - **sensor.dorduncu_ders**
            - sensor.besinci_ders
            - sensor.altinci_ders
            - sensor.yedinci_ders
            - sensor.sekizinci_ders
            - sensor.dokuzuncu_ders
        columns:
          - name: Ders
            attr: friendly_name
          - name: Konu
            prop: state
```

But here is the result:

```
**dorduncu ders** .....
ikinci ders .....
ucuncu ders .....
**birinci ders**.....
besinci ders .....
altinci ders .....
yedinci ders .....
sekizinci ders .....
dokuzuncu ders .....
```

Entities are not same order. And there is no any additional/uniqe field for using "sort_by" option.

**Comment by daringer** [comment]
did you try the following?
```
- type: custom:flex-table-card 
        title: Dersler
        sort_by: friendly_name
        entities:
          include: 
            - **sensor.birinci_ders**
            - sensor.ikinci_ders
            - sensor.ucuncu_ders
            - **sensor.dorduncu_ders**
            - sensor.besinci_ders
            - sensor.altinci_ders
            - sensor.yedinci_ders
            - sensor.sekizinci_ders
            - sensor.dokuzuncu_ders
        columns:
          - name: Ders
            attr: friendly_name
          - name: Konu
            prop: state
```

If you did and this did not match your expectations, can you please show for your above example how the right result should look like?

**Comment by cryptooth** [comment]
Here is the antoher (english) version:

```
- type: custom:flex-table-card 
        title: Food Menu
        entities:
          include: 
            - sensor.morning
            - sensor.noon
            - sensor.evening
        columns:
          - name: Time
            attr: friendly_name
          - name: Menu
            prop: state
```
But results is alphabetical:

```
- sensor.evening
- sensor.morning
- sensor.noon
```

and expected:

```
- sensor.morning
- sensor.noon
- sensor.evening
```

each sensor reading from mySQL database as text (this is daily school menu) 

My expectation is, if the sort_by field is not used, the result must be based on the sensor (include) sequence.
