### ISSUE TITLE
Adding CSS selectors to specific rows based on attribute

### ISSUE THREAD

**Issue by shawly** [custom-cards/flex-table-card#32]
Similar to sorting it would be nice if one could add a CSS selector based on an attribute of the entity, that way it would be possible to apply different styling to rows based on the selector.

For example:
```yaml
type: 'custom:flex-table-card'
entities:
  include: sensor.example.*
columns:
  - prop: state
    name: 'Status'
    as_css_selector: 'tr' # apply state as css selector for row
css:
  tr.state-on: 'color: green' # to make the font of rows with the .state-on selector green
  tr.state-off: 'color: gray' # to make the font of rows with the .state-off selector gray
```

**Comment by daringer** [comment]
mmmh, that's a smart approach, buying it!

* `as_css_selector` feels good (in terms of config-semantics)
* for `tr.state-on` I am not totally convinced this is the right location, let's see if I find a better spot...

**Comment by shawly** [comment]
tr.state-on is just the css selector, since the table row has the class "state-on" you can style it via "tr.state-on", that way you could technically also use `as_css_selector` with something other than tr, td for example to give a cell a specific styling. Here is an example for package tracking:

```yaml
type: 'custom:flex-table-card'
entities:
  include: sensor.parcel.*
columns:
  - prop: state
    name: 'Package delivery'
    as_css_selector: 'tr'
  - attr: carrier
    name: 'Carrier'
    as_css_selector: 'td'
css:
  tr.state-delivered: 'color: gray'
  td.carrier-dhl: 'background: yellow'
```

Would produce html like this:
```html
<table>
...
  <tr class="state-delivered">
    <td>delivered</td>
    <td class="carrier-dhl">
  </tr>
...
</table>
```
