### ISSUE TITLE
Request: Pretty Last Changed Property

### ISSUE THREAD

**Issue by sfgabe** [custom-cards/flex-table-card#33]
Thanks for this card, one feature request: Can you add in some jinja timestamp magic to prettify the "last_changed" property (something like "April 26, 2020, 11:15" or "3 hours, 56 minutes ago")?

<img width="527" alt="Screen Shot 2020-04-26 at 3 35 38 AM" src="https://user-images.githubusercontent.com/36393392/80301024-61ca7800-876f-11ea-952a-870f34468ab8.png">

**Comment by daringer** [comment]
hey hey,

yes you are touching a concept I have in mind for some time now: *column data types*
it is quite a longer story and is also targeting this use case, for now I would suggest using `modify` to get something like "3hours" I currently use something like this:

```yaml
type: 'custom:flex-table-card'
max_rows: 10
sort_by: receivedTS-
clickable: true
title: Time Since Last Received Msg
columns:
  - align: center
    attr: node_id
    icon: 'mdi:z-wave'
    name: NodeID
  - name: Name
    prop: name
  - align: right
    attr: receivedTS
    modify: Math.round((Date.now() - Date.parse(x)) / 36000.) / 100.
    name: Recv. Age
    suffix: ' h'
entities:
  exclude:
    - zwave.unknown_device_*
    - zstick_gen5
    - _tot
  include: zwave.*
```
using this `modify` you will get *hours*, `Date.parse(x)` can be used for many similar approaches. Hope this solves your issue for now, once *column data types* are available this should be possible in a more generic fashion.
