### ISSUE TITLE
[Feature Request]  Format an attribute based on its value

### ISSUE THREAD

**Issue by thorschtn** [custom-cards/flex-table-card#40]
I use the Flex-Table to display a connection overview of the next three train connections including possible delays.

I'm looking for a way to format the delay depending on the value:
0..4 min - green
5..9 min - yellow
10 .. min - red

Is that already possible?

<img width="279" alt="trainconnections" src="https://user-images.githubusercontent.com/16856940/90959272-4c095d00-e49a-11ea-8b75-66e7064837ec.png">

**Comment by benjamfk** [comment]
Do you mean something like so?
![image](https://user-images.githubusercontent.com/64400812/94920982-a7763400-04b7-11eb-84dc-1fa788c4812b.png)

If yes you can do it like so:
Just make multiple if statements to cover green/yellow red and it should work nicely.
```
  - type: 'custom:flex-table-card'
    title: Continuous return
    clickable: false
    entities:
      include: sensor.foobar

    columns:
      - name: Time frame
        data: continuous_return
        modify: x.time_frame

      - name: Return
        data: continuous_return
        modify: >-
          const color = (!isNaN(x.return) && Number(x.return) > 0) ? 'green' : 'red';
          '<span style="color:' + color + ';">' + x.return + '%</span>'
```

**Comment by bcordix** [comment]
I am trying to color change the color of the temp column but have the threshold depend on the type. How would i access the type data being used in the next column?


![image](https://user-images.githubusercontent.com/31374194/97054196-2f8cae00-1539-11eb-8365-e0dac4cea3ac.png)


```
      - type: 'custom:flex-table-card'
        title: 'Disk Temp'
        entities:
          include: sensor.drive_temperature*
        columns:
          - data: Drive
            icon: mdi:harddisk
          - name: Temp
            data: state
            modify: >-
              const color = ((!isNaN(x) && String(x.Type) == 'hdd' && Number(x) < 100) || (!isNaN(x) && String(x.Type) == 'ssd' && Number(x) < 130)) ? 'green' : 'red';
              '<span style="color:' + color + ';">' + x + '°F</span>'
          - name: Type
            data: Type
```
