### ISSUE TITLE
[Question] How to display list of dicts

### ISSUE THREAD

**Issue by csoltenborn** [custom-cards/flex-table-card#47]
I'm trying to display information about outdated HACS components. For this, I have defined some sensors (basically following [this approach](https://community.home-assistant.io/t/update-notifications-core-hacs-supervisor-and-addons/182295/180)) which provide the outdated repositories. Thus, with *Development Tools/Template*, the statement `{{ (state_attr('binary_sensor.hacs_update_issues', 'status')).repositories }}` results in the following output:

```
[{'name': 'FL550/dwd_weather', 'display_name': 'Deutscher Wetterdienst', 'installed_version': 'v1.2.1', 'available_version': 'v1.2.2'}, {'name': 'briis/weatherbit', 'display_name': 'Weatherbit Weather Forecast for Home Assistant', 'installed_version': 'v0.34', 'available_version': 'v0.34.1'}]
```

I'm then trying to use the following code for the UI part:

``` yaml
type: 'custom:auto-entities'
card:
  type: 'custom:flex-table-card'
  title: Pending HACS updates
  columns:
    - name: Component
      data: display_name
    - name: Current version
      data: installed_version
    - name: Latest version
      data: available_version
  sort:
    method: attribute
    attribute: display_name
filter:
  template: >
    {{ (state_attr('binary_sensor.hacs_update_issues', 'status')).repositories }}
```

However, no lines are shown. The same is true for the following template I tried.

```
    {%- for repository in (state_attr('binary_sensor.hacs_update_issues', status')).repositories -%}
      {{ repository}},
    {%- endfor -%} 
```

Is what I'm doing possible at all with flex-table-card? Thanks in advance...

**Comment by patriciowallace** [comment]
did you resolve it ?

**Comment by lezioul** [comment]
Well, i'm interested too.

**Comment by daringer** [comment]
this is currently not really possible, best would be something like that:

```
type: 'custom:flex-table-card'
  title: blub blub
  columns:
    - name: descent-into-object
      data: repositories.foo
```

already tried a naive approach, but this looks like this might be more challenging than expected...

**Comment by EdLeckert** [comment]
@csoltenborn Is this what you want? I realize this is a bit late, but...

![PendingHACSUpdates](https://github.com/custom-cards/flex-table-card/assets/56356940/8a90efdf-d972-4b18-a0cf-003257170fdb)

Created an input_boolean to simulate your example:

![States](https://github.com/custom-cards/flex-table-card/assets/56356940/89c20f1a-77d5-47fc-b64b-4ecbd36f630f)

The Template view:

![Template](https://github.com/custom-cards/flex-table-card/assets/56356940/9b2725b0-502b-4db2-ac06-e4044f7740ca)

The config:

```
type: custom:flex-table-card
title: Pending HACS Updates
sort_by:
  - display_name
entities:
  include: input_boolean.hacs_update_issues
columns:
  - name: Component
    data: status.repositories
    modify: x.display_name
    id: display_name
  - name: Current version
    data: status.repositories
    modify: x.installed_version
  - name: Latest version
    data: status.repositories
    modify: x.available_version
```
