### ISSUE TITLE
Unused entities does not work together with this card

### ISSUE THREAD

**Issue by sjabby** [custom-cards/flex-table-card#5]
With this config added:
```  
- type: 'custom:flex-table-card'
    sort_by: battery_level+
    strict: true
    title: Battery Levels
    entities:
      exclude:
        - unknown_device
      include: zwave.*
    columns:
      - attr: node_id
        name: NodeID
      - name: Name
        prop: name
      - attr: battery_level
        name: Battery Level (%)
```
The Unused Entities view in lovelace does not work. (page is just blank)
Gives this error in console:

```
c51eb71de175ca5b2bc6.chunk.js:1 Uncaught (in promise) TypeError: obj.entities.forEach is not a function
    at addEntities (c51eb71de175ca5b2bc6.chunk.js:1)
    at obj.cards.forEach.card (c51eb71de175ca5b2bc6.chunk.js:1)
    at Array.forEach (<anonymous>)
    at addEntities (c51eb71de175ca5b2bc6.chunk.js:1)
    at config.views.forEach.view (c51eb71de175ca5b2bc6.chunk.js:1)
    at Array.forEach (<anonymous>)
    at computeUsedEntities (c51eb71de175ca5b2bc6.chunk.js:1)
    at computeUnusedEntities (c51eb71de175ca5b2bc6.chunk.js:1)
    at HTMLElement._createElement (c51eb71de175ca5b2bc6.chunk.js:12)
    at HTMLElement.set hass [as hass] (c51eb71de175ca5b2bc6.chunk.js:1)
```
