### ISSUE TITLE
Multiple attributes with same name aren't shown

### ISSUE THREAD

**Issue by DreadN** [custom-cards/flex-table-card#57]
Trying to visualize the "faultType" or also "Since" attribute in this entity.
But nothing is visualized, even if i put comma between same value two times.

If i put this in data:
```
columns:
  - name: Alerts
    data: faultType,since
```

Result is:
"null, null"

If i put this in fata:
```
columns:
  - name: Alerts
    data: faultType
```

Result is:
"undefined"

---------------
Entity data:

```
hvac_modes:
  - 'off'
  - heat
min_temp: 5
max_temp: 35
preset_modes:
  - none
  - temporary
  - permanent
current_temperature: 23
temperature: 30
preset_mode: permanent
status:
  setpoints:
    this_sp_from: '2021-08-04T18:00:00+02:00'
    this_sp_temp: 19.5
    next_sp_from: '2021-08-04T22:30:00+02:00'
    next_sp_temp: 17
  zone_id: '5526090'
  active_faults:
    - faultType: TempZoneSensorLowBattery
      since: '2021-08-03T14:27:54'
    - faultType: TempZoneActuatorLowBattery
      since: '2021-08-03T15:26:48'
  setpoint_status:
    target_heat_temperature: 30
    setpoint_mode: PermanentOverride
  temperature_status:
    temperature: 23.5
    is_available: true
friendly_name: Bagno
icon: mdi:radiator
supported_features: 17
```

**Comment by daringer** [comment]
yes, this is clearly a limitation currently. But you might use `modify` to descent into the lists and select the next unique identifier, roughly like this:
```
columns:
  - name: "1st Alert"
    data: active_faults
   modify: x[0].faultType
  - name: "2nd Alert"
    data: active_faults
   modify: x[1].faultType
```
