### ISSUE TITLE
Sort only takes into consideration the first digit

### ISSUE THREAD

**Issue by bbbenji** [custom-cards/flex-table-card#6]
I am displaying a list of entities and their states and sorting by state. Whenever an entity hits 2 digits, it seems that this card only takes the first digit into account for sorting.

![screenshot_20190218_182921](https://user-images.githubusercontent.com/1678118/52967720-369a0b00-33ab-11e9-87f9-a5160ac08c03.png)

As soon as that first entity hit a state of 9, it popped to the bottom of the list.

**config:**
```
type: 'custom:flex-table-card'
sort_by: state+
title: ZTM
entities:
  include: sensor.ztm*
columns:
  - attr: friendly_name
    name: Number
  - prop: state
    name: Time

```

**Comment by daringer** [comment]
I believe this is a data-type issue. Means you have to make sure that the data is properly converted to a number, if something like this is the case. This depends where your data is coming from and how it is represented there.

To solve this you can make use of `modify` to parse the data to the designated data-type, in this case I would propose something like this:
```
...
columns:
  - prop: state
    name: Time
    modify: parseFloat(x)
```
Now sort_by should work as expected, take a look into issue #7 to see another similar example.
