### ISSUE TITLE
null in attribute breaks the whole card

### ISSUE THREAD

**Issue by T-h-o-m-a-s** [custom-cards/flex-table-card#63]
Don´t know if it is a bug, or me not able to figure out how to exclude entities with null in one of the attributes. 
I have a card displaying all my plant sensors states in a table. Has been working great. Until now, when a few sensors happen to have empty/null value in the "conductivity" attribute. This makes the whole table become empty and only the headers show.  

ATTRIBUTE COLUMN IN DEVELOPER TOOLS/STATES:

problem: moisture low
sensors: 
moisture: sensor.mi_flora_13_moisture
battery: sensor.mi_flora_13_battery
temperature: sensor.mi_flora_13_temperature
conductivity: sensor.mi_flora_13_conductivity
brightness: sensor.mi_flora_13_luminance

unit_of_measurement_dict: 
temperature: °C
brightness: lx
moisture: '%'
battery: '%'

moisture: 1
battery: 86
temperature: 18.8
conductivity: null
brightness: 143
max_brightness: 143
friendly_name: S Dracaena

**Comment by kaizersoje** [comment]
Yes, I have noticed this happen as well. I have noticed that if some entities have the particular attribute but others do not, the ones that do not have that attribute have the value "undefinedundefinedundefined" in the column.

![image](https://user-images.githubusercontent.com/54566217/148720174-fed56b3c-2deb-4ea7-b9cf-0259850290db.png)

```
type: custom:auto-entities
filter:
  include:
    - domain: device_tracker
      attributes:
        source_type: router
      not:
        state: home
  exclude: []
card:
  type: custom:flex-table-card
  title: Offline Devices
  columns:
    - data: ip
      name: IP
  clickable: true
```

**Comment by daringer** [comment]
did you try setting `strict: true` ? the "undefined" stuff is kind of expected behavior, if you would like to filter them out, just take a look at `strict`: https://github.com/custom-cards/flex-table-card/blob/master/docs/example-cfg-sorting-strict.md

**Comment by AleXSR700** [comment]
Does anybody know a different fix than setting `strict: true`?

I have e.g. climate devices that contain data from different sources and if one is unavailable (e.g. the humidity sensor) none of the available data is shown.

Here an example:
<img width="658" alt="image" src="https://github.com/custom-cards/flex-table-card/assets/57034871/28da4fe2-45c4-493f-94da-e34c695cf623">

As you can see, some information is available.

Would a `semi-strict`option be possible? I.e. hide only the undefined data but show the rest?

**Comment by ildar170975** [comment]
> I have e.g. climate devices that contain data from different sources and if one is unavailable (e.g. the humidity sensor) none of the available data is shown.

For simplicity: in flex-table-card one row = one entity.
If some attribute is missing - the whole row will be either not shown (`strict: true`) or just this cell is "undefined" (`strict: false`).

The "undefined" cells (as you know) may be processed by "modify" like this:
```
type: custom:flex-table-card
entities:
  include:
    - sensor.xiaomi_cg_1
columns:
  - name: CO2
    data: co2
  - name: PM2.5
    data: state
  - name: xxx
    data: xxx
  - name: yyy
    data: yyy
    modify: |-
      if(x.length == 0) {
        "-"
      } else {
        x
      }
strict: false
```
![image](https://github.com/custom-cards/flex-table-card/assets/71872483/fc8a7333-94b7-4cc9-ad5e-fe594af9d3c0)


>I.e. hide only the undefined data but show the rest?

How do you imagine that?
There are 3 rows, 5 columns. The 2nd row has a missing 3rd cell - then will the row contain only 4 cells?
Probably you still want to show 5 cells - with an empty 3rd cell. This may be processed as described above.

@daringer 
I wonder why this issue is still open. Displaying "undefined" is an expected behaviour; there are ways to process these values.
