### ISSUE TITLE
Add supports sorting by multiple columns.

### ISSUE THREAD

**Issue by andrewjswan** [custom-cards/flex-table-card#67]
Add supports sorting by multiple columns. Like:
```
card:
  type: custom:flex-table-card
  clickable: true
  sort_by: state-,entity_id+
```
or
```
card:
  type: custom:flex-table-card
  clickable: true
  sort_by: 
    - state-
    - entity_id+
```
