### ISSUE TITLE
Using flex table card with JSON

### ISSUE THREAD

**Issue by galtamur** [custom-cards/flex-table-card#76]
Hello, I am trying to use the Flex Table Card with a sensor providing a JSON coming from a query.
The JSON is as follows:
{"my_data":[{"field_a":"a","field_b":"b"},{"field_a":"a","field_b":"b"}]}
If I configure the card this way:
columns:
  - name: hhh
    data: prova
    modify: x
I see the string of the json as result.

If I configure the card this way:
columns:
  - name: hhh
    data: prova
    modify: x.field_a
I see undefinedundefinedundefined as result.

Where is my error? Or there is an issue somewhere? Thank you for helping.

**Comment by galtamur** [comment]
I tried this, and it's better, but it shows the first record.
In other words, out of:
{"my_data":[{"field_a":"a1","field_b":"b"},{"field_a":"a2","field_b":"b"}]}
it shows a1, whereas I expect to see a table with a column with to rows, with a1 and a2 respectively...
Ideas?

**Comment by daringer** [comment]
oh, nope this will not work to expand the json parsed with `modify` into multiple rows, sorry

**Comment by teskanoo** [comment]
Hi Markus


I too am really struggling with this - it would really be nice to just be able to feed json data into this (totally awesome) card

is this something that could be supported (or already is and I am misunderstanding how to implement it)?

```
    - type: 'custom:flex-table-card'
      title: Load from Json
      strict: false
      columns:
      - data: AA
      - data: BB
      - data: CC

      entities:
        include: [{"AA":9.3,"BB":380,"CC":1300},{"AA":1.3,"BB":180,"CC":1100}]
```

Or this

```
    - type: 'custom:flex-table-card'
      title: Load from Json
     ...
      entities: [{"AA":9.3,"BB":380,"CC":1300},{"AA":1.3,"BB":180,"CC":1100}]
```

Or this

```
    - type: 'custom:flex-table-card'
      title: Load from Json
     ...
      json: [{"AA":9.3,"BB":380,"CC":1300},{"AA":1.3,"BB":180,"CC":1100}]
```

**Comment by EdLeckert** [comment]
To display the JSON in the original comment, from an entity `input_text.mydata` with an attribute `prova`, you could use:

```
type: custom:flex-table-card
title: My Data
entities:
  include: input_text.mydata
columns:
  - name: Field A
    data: prova.my_data
    modify: x.field_a
  - name: Field B
    data: prova.my_data
    modify: x.field_b

```
![MyData](https://github.com/custom-cards/flex-table-card/assets/56356940/47e4590c-900c-4303-bc2a-13ab2d9e2b70)
