### ISSUE TITLE
Eval is evil

### ISSUE THREAD

**Issue by riker09** [custom-cards/flex-table-card#8]
When displaying external sensor data (e.g. fetched from an API) the usage of `eval` will execute malicious code in the context of the trusted HA user interface. I know that this probably very far-fetched but I *strongly* support the plan to

> allow "prefix" and "suffix" for each column to add units or similar stuff, means a simplified version of "modify"

And drop `eval` completely.

**Comment by daringer** [comment]
yeah had similar thoughts about eval(), how about supporting both, means leaving the decision to the user to go for the higher "risk" eval or use "prefix" and/or "suffix" ?

**Comment by riker09** [comment]
That will make everybody happy. The documentation should reflect this and warn the user that the displayed data will pass through `eval` and that it should be avoided, yaddah, yaddah... :slightly_smiling_face:

**Comment by daringer** [comment]
Affirmitive!

* added `prefix`, `suffix` and `align` for cell-text-alignment.
* updated the [README.md](https://github.com/custom-cards/flex-table-card) to make people aware what they are using and the risks
* `modify` will be kept to keep maximum flexibility
* all of the above of course play together smoothly with `modify`

go and get it :smile:

**Comment by riker09** [comment]
Seems to work for me. :slightly_smiling_face: 

![flex-table-align](https://user-images.githubusercontent.com/568497/54297398-0fec8000-45b7-11e9-96f8-a353265b8ed9.png)

## Card config

```yaml
sort_by: diesel_sort_col+
columns:
  - attr_as_list: stations
    modify: x.brand
    name: Tankstelle
  - attr_as_list: stations
    id: diesel_sort_col
    modify: Math.abs(x.diesel)
    hidden: true
  - attr_as_list: stations
    modify: Math.abs(x.diesel).toFixed(2)
    id: diesel_price
    suffix: ' €'
    align: right
    name: Diesel
  - attr_as_list: stations
    modify: Math.abs(x.e5).toFixed(2)
    suffix: ' €'
    align: right
    id: e5_price
    name: Super
  - attr_as_list: stations
    modify: Math.abs(x.dist).toFixed(1)
    align: right
    id: distance
    suffix: ' km'
    name: Distanz
entities:
  include: sensor.gas_prices
max_rows: 10
title: Spritpreise
type: 'custom:flex-table-card'

```
