### ISSUE TITLE
Ability to sort_by column with modify data

### ISSUE THREAD

**Issue by istvnurbn** [custom-cards/flex-table-card#82]
Hi,

I have sensors which are spitting out information like this:

<img width="1022" alt="Screenshot 2022-08-04 at 17 25 11" src="https://user-images.githubusercontent.com/51445152/182886594-10326cb5-fdaa-4d46-823d-b896e20a721a.png">

I have the information populated on the card like so:

<img width="467" alt="Screenshot 2022-08-04 at 17 31 09" src="https://user-images.githubusercontent.com/51445152/182887059-949d9102-b883-4cb9-9908-fe166650b058.png">

As you can see the departure times are a bit jumbled and I would like to sort the table based on that. However the only `data` I have is `vehicles` from which I extract the departure time with the `modify` option:

```YAML
type: custom:flex-table-card
sort_by: vehicles
max_rows: 8
entities:
  include:
    - sensor.bkk_fay_to_downtown_buses
    - sensor.bkk_fay_to_downtown_tram
columns:
  - name: Route
    data: vehicles
    modify: x.routeid
  - name: Where
    data: vehicles
    modify: x.headsign
  - con: mdi:clock
    name: Departure
    align: right
    data: vehicles
    modify: x.in + 'm' + ' | ' + x.attime
```

So it would be great if you could add the ability to sort data based on the `modify` option of a given column.
