### ISSUE TITLE
[Feature Request] Format/add indendation

### ISSUE THREAD

**Issue by bcutter** [custom-cards/flex-table-card#83]
Hi,

as I was hoping to find a topic in the famous https://community.home-assistant.io/c/projects/frontend section (which unfortunately does not exist) I need to ask this question - or let's call it feature request - here:

Allow to add an indendation (e. g. as option `indendation: '   '` which would give 3 spaces) starting with the first line break (\n) so this...

![grafik](https://user-images.githubusercontent.com/13799156/189504569-b7c09807-287b-491d-9d25-4fb0fdc73a13.png)

```
type: custom:flex-table-card
title: ''
clickable: true
entities:
  include: sensor.updates_server
  exclude: null
columns:
  - name: ' Available updates'
    data: packages
    prefix: '🟢 '
    suffix: ''
    align: left
    icon: mdi:package-down
```

can look like this, which would greatly enhance the readability:

![grafik](https://user-images.githubusercontent.com/13799156/189504605-a0c5c34c-727f-4fde-ac90-4cdf2f42e838.png)

I read all the styling sections twice but could not find an existing solution for this.
In case there already is a working solution for this, please let me know.
