### ISSUE TITLE
How to select object-based Attribute?

### ISSUE THREAD

**Issue by ChristophCaina** [custom-cards/flex-table-card#87]
Hi,
I've just switched from the attribues card to the flex-table-card in the hope, it would allow me to fix one of my current issues...
Unfortunately, it seems that I am not able to wirte down my yaml in a way that I can do, what I want ... maybe, someone can give me some help?

I have a sensor with the following attributes:
```
engine:
  engine_type: iV
  power_in_kw: 132
  battery_capacity_kwh: 62
model: ŠKODA Enyaq 60 iV 60/2022-05-17
assumed_state: true
icon: mdi:information-outline
friendly_name: Enyaq iV60 Car Info
```

Now, I want to display engine.power_in_kw as well as engine.battery_capacity within the flex table.

it should be something like that:
| | |
|----|----|
| power_in_kw | 132 |
| battery_capacity_kwh | 62 |
