### ISSUE TITLE
Card updates itself all the time - even if it is not needed

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/flex-table-card#88]
Create this card:
```
  - type: custom:flex-table-card
    entities:
      include: input_number.test_number
    columns:
      - name: hhh
        data: state
```
where `input_number.test_number` - some helper.

![image](https://user-images.githubusercontent.com/71872483/190835257-2b57bf52-3880-49e7-87e3-51e2174fb9b8.png)

Open Code Inspector (or whatever it is called in your browser).
Select "tbody" element, then try to expand it.
After expanding to the bottommost element "td", the "tr" element collapses again.
It happens when rows  are updated.
You can see how it flickers:
![fle](https://user-images.githubusercontent.com/71872483/190835009-924e9bdf-f33d-4c02-a899-6c115396dad2.gif)

But there is no need to update the table since it's content not changed.

This updating takes some CPU's time.

What happens when there are many rows in the table?
```
  - type: custom:flex-table-card
    entities:
      include:
        - input_number.test_number
        - input_number.test_number_2
        - input_number.test_number_3
    columns:
      - name: hhh
        data: state
```
Yes - all rows are flickering:
![fle2](https://user-images.githubusercontent.com/71872483/190835350-412b5b83-c07c-42fd-96ef-0e8183a46282.gif)
