### ISSUE TITLE
How to exclude rows by state

### ISSUE THREAD

**Issue by Bluscream** [custom-cards/flex-table-card#92]
```yaml
type: custom:flex-table-card
entities:
  include: .*android.*
columns:
  - name: Name
    data: name
  - name: State
    data: state
    exclude: 'unknown'
```

This doesn't seem to work

**Comment by ildar170975** [comment]
A possibility to include/exclude by a state is not supported.
But it is possible in combination with `auto-entities`.
Check an example in Docs related to `auto-entities` and specify any filters you need.

**Comment by Bluscream** [comment]
Oh yes, thank you i managed to do it like this:
```
type: custom:auto-entities
filter:
  include:
    - entity_id: /.*android.*/
  exclude:
    - state: unknown
    - state: 'off'
    - state: ''
    - state: '0'
    - state: unavailable
card:
  type: custom:flex-table-card
  title: Auto Entities Example
  clickable: true
  columns:
    - data: friendly_name
      name: Friendly Name
    - data: state
      name: State
```
