### ISSUE TITLE
Attribute named 'name', similar to your fix for attribute named state?

### ISSUE THREAD

**Issue by deepcoder** [custom-cards/flex-table-card#95]
I have a attribute named 'name' and I am not able to figure out how to enter as the data: value.

https://github.com/custom-cards/flex-table-card/issues/51

Thank you for your work on this card, very useful!

**Comment by ildar170975** [comment]
Post a picture of this sensor from Dev tools -> set state

**Comment by deepcoder** [comment]
Hope this is the information you are requesting. Naming an attribute 'name' appear to cause the clash with the 'name' of the sensor which is provided by the integration cited at URL below. Lovelace yaml code shown below to generate the output shown. Desired output would be to have the column named 'Name' contain the contents of the attribute named 'name' not the sensor nice name.

```
    - type: entities
      entities:
        - sensor.rocket_launch_1
        - sensor.rocket_launch_2
        - sensor.rocket_launch_3
        - sensor.rocket_launch_4
        - sensor.rocket_launch_5

    - type: custom:flex-table-card
      title: URL
      entities:
        include: sensor.rocket_launch*
      columns:
        - name: State
          data: state
        - name: Name
          data: name
        - name: Vehicle
          data: vehicle
        - name: Launch Pad
          data: launch_pad
        - name: Estimated Launch Date
          data: est_launch_date
```

[https://github.com/djtimca/harocketlaunchlive](url)


![tab02](https://user-images.githubusercontent.com/1409547/219880014-9ed4ff81-61c0-483e-a723-a6498d2557b0.jpg)

![tab01](https://user-images.githubusercontent.com/1409547/219880023-38740d19-83f0-47f5-aa1e-1c2ea7578182.jpg)
