### ISSUE TITLE
Allow regex for data source in coloumns

### ISSUE THREAD

**Issue by MS-HACS** [custom-cards/flex-table-card#97]
Following your basic example I tried to create a table with the battery level of all devices - most of them mobiles with HA app installed.

The sensors giving the battery level are named in the form `sensor.<mobile>_battery_level` or `sensor.battery_level_<number>`.

So I would have to add each sensor manually instead of letting the table card generate it what is the generel purpose of this great extension.

So what I would like to have is the ability to define some sort of expression, e.g.

```
columns:
  - name: Battery Level
    data: *_battery_level,battery_level_*
...
```
